name: Check Renovate config
on:
  push:
    paths:
      - 'renovate.json'
  pull_request:
    paths:
      - 'renovate.json'

jobs:
  check-renovate-config:
    name: Configuration check
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup npm
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4

      - name: Validate config file
        run: |
          npx --yes --package renovate -- renovate-config-validator
